### PR TITLE
refactor: support vite 2

### PR DESCRIPTION
**Pull request by antfu**

### CODE REVIEW

**Comment by antfu** [comment]
@knightly-bot build this

**Comment by stafyniaksacha** [comment]
Hello @antfu ! I love the idea of knightly :) 
If I understood, I can test it with something like this ?
```
  "vite-plugin-voie": "npm:@knightly/vite-plugin-voie",
  "voie-pages": "npm:@knightly/voie-pages"
```

**Comment by antfu** [comment]
@stafyniaksacha Knightly didn't trigger for some reason, I will have a look later. You can use this for now

```json
"vite-plugin-voie": "npm:@antfu/vite-plugin-voie"
```

And use the official `voie-pages`

**Comment by brattonross** [comment]
Great work, thank you! 😀

**Pull request merged**
